name: Build static indexes (photos.json & gps.json)
on:
  push:
    branches: [ main ]
    paths:
      - "photos/**"
      - "GPS/**"
      - ".github/workflows/build-index.yml"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate indexes
        run: |
          import os, re, json, time
          from pathlib import Path
          OWNER="Fatma-Alhosani"
          REPO="drone-dashboard"
          BRANCH="main"
          def parse_ts_to_ms(key:str):
              import datetime
              m = re.match(r'^(\d{4}-\d{2}-\d{2})[|_](\d{2})-(\d{2})-(\d{2})$', key)
              if not m:
                  m = re.match(r'^(\d{4}-\d{2}-\d{2}).?(\d{2})[-:](\d{2})[-:](\d{2})$', key)
              if not m: return None
              dt = datetime.datetime(int(m.group(1)[0:4]), int(m.group(1)[5:7]), int(m.group(1)[8:10]),
                                     int(m.group(2)), int(m.group(3)), int(m.group(4)))
              return int(dt.replace(tzinfo=datetime.timezone.utc).timestamp()*1000)
          def base_name(p): 
              stem = Path(p).name
              i = stem.rfind('.')
              return stem[:i] if i>0 else stem
          def parse_coords(text:str):
              m = re.search(r'lat\D*(-?\d+(?:\.\d+)?)\D*lon\D*(-?\d+(?:\.\d+)?)', text, re.I)
              if not m:
                  m = re.search(r'(-?\d+(?:\.\d+)?)\D*,\D*(-?\d+(?:\.\d+)?)', text)
              if not m:
                  nums = re.findall(r'-?\d+(?:\.\d+)?', text)
                  if len(nums)>=2: m = [None, nums[0], nums[1]]
              if not m: return None
              lat, lon = float(m[1]), float(m[2])
              if abs(lat)>90 or abs(lon)>180: return None
              return dict(lat=lat, lon=lon)
          raw_base = f"https://raw.githubusercontent.com/{OWNER}/{REPO}/{BRANCH}"
          photos = []
          pdir = Path("photos")
          if pdir.exists():
              for p in sorted(pdir.iterdir()):
                  if p.is_file() and p.suffix.lower() in (".jpg",".jpeg",".png",".webp"):
                      key = base_name(p.name)
                      ts = parse_ts_to_ms(key)
                      if ts is None: continue
                      photos.append({
                        "name": p.name,
                        "key": key,
                        "tsMs": ts,
                        "url": f"{raw_base}/photos/{p.name}",
                        "html_url": f"https://github.com/{OWNER}/{REPO}/blob/{BRANCH}/photos/{p.name}"
                      })
          gps = []
          gdir = Path("GPS")
          if gdir.exists():
              for t in sorted(gdir.iterdir()):
                  if t.is_file() and t.suffix.lower()==".txt":
                      key = base_name(t.name)
                      ts = parse_ts_to_ms(key)
                      if ts is None: continue
                      try:
                          txt = t.read_text(encoding="utf-8", errors="ignore")
                      except:
                          continue
                      c = parse_coords(txt)
                      if not c: continue
                      gps.append({
                        "key": key, "tsMs": ts,
                        "lat": c["lat"], "lon": c["lon"],
                        "path": f"GPS/{t.name}",
                        "html_url": f"https://github.com/{OWNER}/{REPO}/blob/{BRANCH}/GPS/{t.name}"
                      })
          photos.sort(key=lambda x:x["tsMs"])
          gps.sort(key=lambda x:x["tsMs"])
          Path("photos.json").write_text(json.dumps(photos, indent=2), encoding="utf-8")
          Path("gps.json").write_text(json.dumps(gps, indent=2), encoding="utf-8")
          print(f"photos: {len(photos)} | gps: {len(gps)}")
        shell: python

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add photos.json gps.json
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update indexes"
            git push
          fi
